<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="Windows 7" host="HIBACL54346"><DocLocation><![CDATA[D:\E drive\QTP_Training_Data\Capgemini Training\OutPutData_Example]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[OutPutData_Example]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[BookFlight]]></AName>
<AIter rID="T5" iterID="1" isCountable="False" >
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:34]]></Time>
<TimeTick>1528196854</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:34]]></Time>
<TimeTick>1528196854</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="BookFlight" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:34]]></Time>
<TimeTick>1528196854</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="BookFlight" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:34]]></Time>
<TimeTick>1528196854</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="BookFlight" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:35]]></Time>
<TimeTick>1528196855</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="BookFlight" SourceLine="4" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:35]]></Time>
<TimeTick>1528196855</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="BookFlight" SourceLine="5" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:36]]></Time>
<TimeTick>1528196856</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="BookFlight" SourceLine="6" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:36]]></Time>
<TimeTick>1528196856</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="BookFlight" SourceLine="9" >
<Disp><![CDATA[SELECT FLIGHT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:36]]></Time>
<TimeTick>1528196856</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="BookFlight" SourceLine="12" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:36]]></Time>
<TimeTick>1528196856</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="BookFlight" SourceLine="13" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:37]]></Time>
<TimeTick>1528196857</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="BookFlight" SourceLine="14" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:37]]></Time>
<TimeTick>1528196857</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" Source="BookFlight" SourceLine="15" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Order 216 completed]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfObject]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:42]]></Time>
<TimeTick>1528196862</TimeTick>
<HtmlStep rID="T19">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Output Value "Order 328 completed": </span><span class="DoneHigh">Done</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 6/5/2018 - 16:37:42</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">Order 328 completed Results&nbsp;</td></tr>
<tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Captured Value&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Type&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Name&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td class="text">name&nbsp;</td>
				<td class="text">Order 337 completed&nbsp;</td>
				<td class="text">DataTable&nbsp;</td>
				<td class="text">Order_No&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1528196862</TimeTick>
<NodeArgs eType="Verification" icon="11" nRep="32" Source="BookFlight" SourceLine="20" >
<Disp><![CDATA[Output "Order 328 completed"]]></Disp>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="11" nRep="31" Source="BookFlight" SourceLine="20" >
<Disp><![CDATA[Order 216 completed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:51]]></Time>
<TimeTick>1528196871</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="BookFlight" SourceLine="30" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="BookFlight" SourceLine="1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="8" >
<Disp><![CDATA[BookFlight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T21" iterID="2" isCountable="False" >
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:52]]></Time>
<TimeTick>1528196872</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:52]]></Time>
<TimeTick>1528196872</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="BookFlight" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:52]]></Time>
<TimeTick>1528196872</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" Source="BookFlight" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:52]]></Time>
<TimeTick>1528196872</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="BookFlight" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:53]]></Time>
<TimeTick>1528196873</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="45" Source="BookFlight" SourceLine="4" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:53]]></Time>
<TimeTick>1528196873</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" Source="BookFlight" SourceLine="5" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:54]]></Time>
<TimeTick>1528196874</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" Source="BookFlight" SourceLine="6" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:54]]></Time>
<TimeTick>1528196874</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" Source="BookFlight" SourceLine="9" >
<Disp><![CDATA[SELECT FLIGHT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:54]]></Time>
<TimeTick>1528196874</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" Source="BookFlight" SourceLine="12" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:54]]></Time>
<TimeTick>1528196874</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="BookFlight" SourceLine="13" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:55]]></Time>
<TimeTick>1528196875</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" Source="BookFlight" SourceLine="14" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:55]]></Time>
<TimeTick>1528196875</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="BookFlight" SourceLine="15" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[6/5/2018 - 16:37:57]]></Time>
<TimeTick>1528196877</TimeTick>
<NodeArgs eType="General" icon="12" nRep="59" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="38" Source="BookFlight" SourceLine="1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="36" >
<Disp><![CDATA[BookFlight Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="6/5/2018 - 16:37:33" eTime="6/5/2018 - 16:37:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[BookFlight Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[OutPutData_Example Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="6/5/2018 - 16:37:32" eTime="6/5/2018 - 16:37:57" passed="0" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test OutPutData_Example Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>