<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="Windows 7" host="HIBACL54346"><DocLocation><![CDATA[D:\E drive\QTP_Training_Data\Capgemini Training\TestCombinationGenerator_Example]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TestCombinationGenerator_Example]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:58:59]]></Time>
<TimeTick>1527672539</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:58:59]]></Time>
<TimeTick>1527672539</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:58:59]]></Time>
<TimeTick>1527672539</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:00]]></Time>
<TimeTick>1527672540</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:00]]></Time>
<TimeTick>1527672540</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:00]]></Time>
<TimeTick>1527672540</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:00]]></Time>
<TimeTick>1527672540</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sid"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:01]]></Time>
<TimeTick>1527672541</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="6" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:01]]></Time>
<TimeTick>1527672541</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="24" Source="Action1" SourceLine="7" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Order 92 completed.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:07]]></Time>
<TimeTick>1527672547</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Order 92 completed.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:07]]></Time>
<TimeTick>1527672547</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="Action1" SourceLine="12" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/30/2018 - 14:58:58" eTime="5/30/2018 - 14:59:07" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[TestCombinationGenerator_Example Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T16" iterID="2" >
<Action rID="T17">
<AName><![CDATA[Action1]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:08]]></Time>
<TimeTick>1527672548</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:08]]></Time>
<TimeTick>1527672548</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:08]]></Time>
<TimeTick>1527672548</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:09]]></Time>
<TimeTick>1527672549</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:09]]></Time>
<TimeTick>1527672549</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:09]]></Time>
<TimeTick>1527672549</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:09]]></Time>
<TimeTick>1527672549</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="45" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Phillip"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:10]]></Time>
<TimeTick>1527672550</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="Action1" SourceLine="6" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:10]]></Time>
<TimeTick>1527672550</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" Source="Action1" SourceLine="7" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Order 92 completed.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:16]]></Time>
<TimeTick>1527672556</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Order 92 completed.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:16]]></Time>
<TimeTick>1527672556</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" Source="Action1" SourceLine="12" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/30/2018 - 14:59:08" eTime="5/30/2018 - 14:59:16" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="32" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="31" >
<Disp><![CDATA[TestCombinationGenerator_Example Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T29" iterID="3" >
<Action rID="T30">
<AName><![CDATA[Action1]]></AName>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:16]]></Time>
<TimeTick>1527672556</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:16]]></Time>
<TimeTick>1527672556</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="60" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:17]]></Time>
<TimeTick>1527672557</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:17]]></Time>
<TimeTick>1527672557</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:17]]></Time>
<TimeTick>1527672557</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:17]]></Time>
<TimeTick>1527672557</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:18]]></Time>
<TimeTick>1527672558</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mariah"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:18]]></Time>
<TimeTick>1527672558</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="Action1" SourceLine="6" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:18]]></Time>
<TimeTick>1527672558</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" Source="Action1" SourceLine="7" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Order 92 completed.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:24]]></Time>
<TimeTick>1527672564</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Order 92 completed.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:25]]></Time>
<TimeTick>1527672565</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" Source="Action1" SourceLine="12" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="59" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/30/2018 - 14:59:16" eTime="5/30/2018 - 14:59:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="57" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="56" >
<Disp><![CDATA[TestCombinationGenerator_Example Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T42" iterID="4" >
<Action rID="T43">
<AName><![CDATA[Action1]]></AName>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:25]]></Time>
<TimeTick>1527672565</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:25]]></Time>
<TimeTick>1527672565</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="85" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:25]]></Time>
<TimeTick>1527672565</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="87" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:26]]></Time>
<TimeTick>1527672566</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="89" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:26]]></Time>
<TimeTick>1527672566</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="91" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:26]]></Time>
<TimeTick>1527672566</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="93" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:26]]></Time>
<TimeTick>1527672566</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="95" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gabriel"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:27]]></Time>
<TimeTick>1527672567</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" Source="Action1" SourceLine="6" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:27]]></Time>
<TimeTick>1527672567</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="99" Source="Action1" SourceLine="7" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Order 92 completed.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:33]]></Time>
<TimeTick>1527672573</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="101" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Order 92 completed.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:33]]></Time>
<TimeTick>1527672573</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" Source="Action1" SourceLine="12" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="84" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/30/2018 - 14:59:25" eTime="5/30/2018 - 14:59:33" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="82" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="81" >
<Disp><![CDATA[TestCombinationGenerator_Example Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T55" iterID="5" >
<Action rID="T56">
<AName><![CDATA[Action1]]></AName>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:34]]></Time>
<TimeTick>1527672574</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:34]]></Time>
<TimeTick>1527672574</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="110" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:34]]></Time>
<TimeTick>1527672574</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:34]]></Time>
<TimeTick>1527672574</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="114" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:34]]></Time>
<TimeTick>1527672574</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="116" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:35]]></Time>
<TimeTick>1527672575</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="118" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:35]]></Time>
<TimeTick>1527672575</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="120" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Curtis"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:35]]></Time>
<TimeTick>1527672575</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="122" Source="Action1" SourceLine="6" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:36]]></Time>
<TimeTick>1527672576</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="124" Source="Action1" SourceLine="7" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Order 92 completed.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:42]]></Time>
<TimeTick>1527672582</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="126" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Order 92 completed.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:42]]></Time>
<TimeTick>1527672582</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="128" Source="Action1" SourceLine="12" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="109" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/30/2018 - 14:59:33" eTime="5/30/2018 - 14:59:42" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="107" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="106" >
<Disp><![CDATA[TestCombinationGenerator_Example Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T68" iterID="6" >
<Action rID="T69">
<AName><![CDATA[Action1]]></AName>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:42]]></Time>
<TimeTick>1527672582</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:42]]></Time>
<TimeTick>1527672582</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="135" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:43]]></Time>
<TimeTick>1527672583</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="137" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:43]]></Time>
<TimeTick>1527672583</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="139" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:43]]></Time>
<TimeTick>1527672583</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="141" Source="Action1" SourceLine="3" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:43]]></Time>
<TimeTick>1527672583</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="143" Source="Action1" SourceLine="4" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/30/2018 - 14:59:43]]></Time>
<TimeTick>1527672583</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="145" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>