<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="Windows 7" host="HIBACL54346"><DocLocation><![CDATA[D:\E drive\QTP_Training_Data\Capgemini Training\TestCombinationGenerator_DateField_Example]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TestCombinationGenerator_DateField_Example]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:30]]></Time>
<TimeTick>1527742950</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:30]]></Time>
<TimeTick>1527742950</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:37]]></Time>
<TimeTick>1527742957</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:40]]></Time>
<TimeTick>1527742960</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["17-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:40]]></Time>
<TimeTick>1527742960</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:40]]></Time>
<TimeTick>1527742960</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:41]]></Time>
<TimeTick>1527742961</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:20" eTime="5/31/2018 - 10:32:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T12" iterID="2" >
<Action rID="T13">
<AName><![CDATA[Action1]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:42]]></Time>
<TimeTick>1527742962</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:42]]></Time>
<TimeTick>1527742962</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:42]]></Time>
<TimeTick>1527742962</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:43]]></Time>
<TimeTick>1527742963</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["08-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:43]]></Time>
<TimeTick>1527742963</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:43]]></Time>
<TimeTick>1527742963</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:44]]></Time>
<TimeTick>1527742964</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="26" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:41" eTime="5/31/2018 - 10:32:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="24" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="23" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T21" iterID="3" >
<Action rID="T22">
<AName><![CDATA[Action1]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:44]]></Time>
<TimeTick>1527742964</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:45]]></Time>
<TimeTick>1527742965</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:45]]></Time>
<TimeTick>1527742965</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:45]]></Time>
<TimeTick>1527742965</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["04-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:46]]></Time>
<TimeTick>1527742966</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:46]]></Time>
<TimeTick>1527742966</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:46]]></Time>
<TimeTick>1527742966</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="43" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:44" eTime="5/31/2018 - 10:32:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="41" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="40" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T30" iterID="4" >
<Action rID="T31">
<AName><![CDATA[Action1]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:47]]></Time>
<TimeTick>1527742967</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:47]]></Time>
<TimeTick>1527742967</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:47]]></Time>
<TimeTick>1527742967</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:48]]></Time>
<TimeTick>1527742968</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="65" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["16-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:48]]></Time>
<TimeTick>1527742968</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:48]]></Time>
<TimeTick>1527742968</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:49]]></Time>
<TimeTick>1527742969</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="60" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:47" eTime="5/31/2018 - 10:32:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="58" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="57" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T39" iterID="5" >
<Action rID="T40">
<AName><![CDATA[Action1]]></AName>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:49]]></Time>
<TimeTick>1527742969</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:49]]></Time>
<TimeTick>1527742969</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="78" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:50]]></Time>
<TimeTick>1527742970</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="80" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:50]]></Time>
<TimeTick>1527742970</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["11-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:51]]></Time>
<TimeTick>1527742971</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="84" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:51]]></Time>
<TimeTick>1527742971</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:51]]></Time>
<TimeTick>1527742971</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="77" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:49" eTime="5/31/2018 - 10:32:51" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="75" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="74" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T48" iterID="6" >
<Action rID="T49">
<AName><![CDATA[Action1]]></AName>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:52]]></Time>
<TimeTick>1527742972</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:52]]></Time>
<TimeTick>1527742972</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="95" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:52]]></Time>
<TimeTick>1527742972</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:53]]></Time>
<TimeTick>1527742973</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["02-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:53]]></Time>
<TimeTick>1527742973</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="101" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:53]]></Time>
<TimeTick>1527742973</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:54]]></Time>
<TimeTick>1527742974</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="105" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="94" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:51" eTime="5/31/2018 - 10:32:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="92" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="91" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T57" iterID="7" >
<Action rID="T58">
<AName><![CDATA[Action1]]></AName>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:54]]></Time>
<TimeTick>1527742974</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:54]]></Time>
<TimeTick>1527742974</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="112" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:55]]></Time>
<TimeTick>1527742975</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="114" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:55]]></Time>
<TimeTick>1527742975</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="116" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["03-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:55]]></Time>
<TimeTick>1527742975</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="118" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:56]]></Time>
<TimeTick>1527742976</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="120" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:56]]></Time>
<TimeTick>1527742976</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="122" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="111" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:54" eTime="5/31/2018 - 10:32:56" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="109" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="108" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 7 (Row 7)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T66" iterID="8" >
<Action rID="T67">
<AName><![CDATA[Action1]]></AName>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:57]]></Time>
<TimeTick>1527742977</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:57]]></Time>
<TimeTick>1527742977</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="129" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:57]]></Time>
<TimeTick>1527742977</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="131" Source="Action1" SourceLine="1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:57]]></Time>
<TimeTick>1527742977</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="133" Source="Action1" SourceLine="2" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["19-Jun-2018"]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:58]]></Time>
<TimeTick>1527742978</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="135" Source="Action1" SourceLine="3" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:58]]></Time>
<TimeTick>1527742978</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="137" Source="Action1" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[BACK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:59]]></Time>
<TimeTick>1527742979</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="139" Source="Action1" SourceLine="5" >
<Disp><![CDATA[BACK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="128" Source="Action1" SourceLine="0" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/31/2018 - 10:32:56" eTime="5/31/2018 - 10:32:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="126" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="125" >
<Disp><![CDATA[TestCombinationGenerator_DateField_Example Iteration 8 (Row 8)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T75" iterID="9" >
<Action rID="T76">
<AName><![CDATA[Action1]]></AName>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:59]]></Time>
<TimeTick>1527742979</TimeTick>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2018 - 10:32:59]]></Time>
<TimeTick>1527742979</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="146" Source="Action1" SourceLine="0" >