<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="Windows 7" host="HIBACL54346"><DocLocation><![CDATA[D:\E drive\QTP_Training_Data\Capgemini Training\DataTable_Test_Combination_Generator_Example]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[DataTable_Test_Combination_Generator_Example]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:13]]></Time>
<TimeTick>1528180573</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:13]]></Time>
<TimeTick>1528180573</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Action1" SourceLine="3" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:14]]></Time>
<TimeTick>1528180574</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="4" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:14]]></Time>
<TimeTick>1528180574</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="5" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:15]]></Time>
<TimeTick>1528180575</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:15]]></Time>
<TimeTick>1528180575</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:15]]></Time>
<TimeTick>1528180575</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Action1" SourceLine="9" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:16]]></Time>
<TimeTick>1528180576</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:16]]></Time>
<TimeTick>1528180576</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="Action1" SourceLine="11" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:16]]></Time>
<TimeTick>1528180576</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="Action1" SourceLine="12" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:17]]></Time>
<TimeTick>1528180577</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Action1" SourceLine="13" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:17]]></Time>
<TimeTick>1528180577</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:18]]></Time>
<TimeTick>1528180578</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="Action1" SourceLine="15" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:18]]></Time>
<TimeTick>1528180578</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="Action1" SourceLine="16" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:18]]></Time>
<TimeTick>1528180578</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="39" Source="Action1" SourceLine="17" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" Source="Action1" SourceLine="3" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/5/2018 - 12:06:12" eTime="6/5/2018 - 12:06:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[DataTable_Test_Combination_Generator_Example Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T20" iterID="2" >
<Action rID="T21">
<AName><![CDATA[Action1]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:19]]></Time>
<TimeTick>1528180579</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:19]]></Time>
<TimeTick>1528180579</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" Source="Action1" SourceLine="3" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:20]]></Time>
<TimeTick>1528180580</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="Action1" SourceLine="4" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:20]]></Time>
<TimeTick>1528180580</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="Action1" SourceLine="5" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:21]]></Time>
<TimeTick>1528180581</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:21]]></Time>
<TimeTick>1528180581</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:21]]></Time>
<TimeTick>1528180581</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" Source="Action1" SourceLine="9" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:22]]></Time>
<TimeTick>1528180582</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:22]]></Time>
<TimeTick>1528180582</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" Source="Action1" SourceLine="11" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:23]]></Time>
<TimeTick>1528180583</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" Source="Action1" SourceLine="12" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:23]]></Time>
<TimeTick>1528180583</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" Source="Action1" SourceLine="13" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:23]]></Time>
<TimeTick>1528180583</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:24]]></Time>
<TimeTick>1528180584</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="72" Source="Action1" SourceLine="15" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:24]]></Time>
<TimeTick>1528180584</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" Source="Action1" SourceLine="16" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:24]]></Time>
<TimeTick>1528180584</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="76" Source="Action1" SourceLine="17" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="49" Source="Action1" SourceLine="3" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/5/2018 - 12:06:18" eTime="6/5/2018 - 12:06:24" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="43" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="42" >
<Disp><![CDATA[DataTable_Test_Combination_Generator_Example Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T37" iterID="3" >
<Action rID="T38">
<AName><![CDATA[Action1]]></AName>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:25]]></Time>
<TimeTick>1528180585</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:25]]></Time>
<TimeTick>1528180585</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="86" Source="Action1" SourceLine="3" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:26]]></Time>
<TimeTick>1528180586</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="88" Source="Action1" SourceLine="4" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:26]]></Time>
<TimeTick>1528180586</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="90" Source="Action1" SourceLine="5" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Seattle"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:27]]></Time>
<TimeTick>1528180587</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:27]]></Time>
<TimeTick>1528180587</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:27]]></Time>
<TimeTick>1528180587</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" Source="Action1" SourceLine="9" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:28]]></Time>
<TimeTick>1528180588</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:28]]></Time>
<TimeTick>1528180588</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="100" Source="Action1" SourceLine="11" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:29]]></Time>
<TimeTick>1528180589</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" Source="Action1" SourceLine="12" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:29]]></Time>
<TimeTick>1528180589</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="104" Source="Action1" SourceLine="13" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:29]]></Time>
<TimeTick>1528180589</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="106" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:30]]></Time>
<TimeTick>1528180590</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="108" Source="Action1" SourceLine="15" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:30]]></Time>
<TimeTick>1528180590</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="110" Source="Action1" SourceLine="16" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:30]]></Time>
<TimeTick>1528180590</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="112" Source="Action1" SourceLine="17" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="85" Source="Action1" SourceLine="3" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/5/2018 - 12:06:24" eTime="6/5/2018 - 12:06:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="80" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="79" >
<Disp><![CDATA[DataTable_Test_Combination_Generator_Example Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T54" iterID="4" >
<Action rID="T55">
<AName><![CDATA[Action1]]></AName>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:31]]></Time>
<TimeTick>1528180591</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:31]]></Time>
<TimeTick>1528180591</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="123" Source="Action1" SourceLine="3" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:32]]></Time>
<TimeTick>1528180592</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="125" Source="Action1" SourceLine="4" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:32]]></Time>
<TimeTick>1528180592</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="127" Source="Action1" SourceLine="5" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:33]]></Time>
<TimeTick>1528180593</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="129" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Zurich"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:33]]></Time>
<TimeTick>1528180593</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="131" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[datePicker.SetDate]]></Obj>
<Details plainTxt="False" ><![CDATA["14-Jun-2018"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:33]]></Time>
<TimeTick>1528180593</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="133" Source="Action1" SourceLine="9" >
<Disp><![CDATA[datePicker.SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:34]]></Time>
<TimeTick>1528180594</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="135" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:34]]></Time>
<TimeTick>1528180594</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="137" Source="Action1" SourceLine="11" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:35]]></Time>
<TimeTick>1528180595</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="139" Source="Action1" SourceLine="12" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:36]]></Time>
<TimeTick>1528180596</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="141" Source="Action1" SourceLine="13" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:36]]></Time>
<TimeTick>1528180596</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="143" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:36]]></Time>
<TimeTick>1528180596</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="145" Source="Action1" SourceLine="15" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:37]]></Time>
<TimeTick>1528180597</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="147" Source="Action1" SourceLine="16" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:37]]></Time>
<TimeTick>1528180597</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="149" Source="Action1" SourceLine="17" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="122" Source="Action1" SourceLine="3" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/5/2018 - 12:06:30" eTime="6/5/2018 - 12:06:37" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="116" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="115" >
<Disp><![CDATA[DataTable_Test_Combination_Generator_Example Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T71" iterID="5" >
<Action rID="T72">
<AName><![CDATA[Action1]]></AName>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:38]]></Time>
<TimeTick>1528180598</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:38]]></Time>
<TimeTick>1528180598</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="160" Source="Action1" SourceLine="3" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:39]]></Time>
<TimeTick>1528180599</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="162" Source="Action1" SourceLine="4" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/5/2018 - 12:06:39]]></Time>
<TimeTick>1528180599</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="164" Source="Action1" SourceLine="5" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>